version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: campusreach
      POSTGRES_PASSWORD: campusreach
      POSTGRES_DB: campusreach
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "campusreach"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
